# This is a basic workflow to help you get started with Actions

name: Test Webhook Every Minute - Test

# Controls when the workflow will run
on:
  schedule: # “End of the day”
    - cron: "* * * * *"
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: production
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Send Emails to Greeting Recepients
        uses: Satak/webrequest-action@v1.2.3
        with:
          # Web request URL endpoint
          url: "https://api.greetings.dumbstartupideas.com/platform/test/dispatch"
          method: POST
          headers: '{"key": "${{ secrets.EMAIL_WEBHOOK_AUTH }}"}'
